apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: global-vars
        optional: false
resources:
  - my-configmap.yaml
